const fanKitCharacterCodeEntries = [
  [1, ['Jackie', '재키']],
  [2, ['Aya', '아야']],
  [3, ['Hyunwoo', '현우']],
  [4, ['Magnus', '매그너스']],
  [5, ['Fiora', '피오라']],
  [6, ['Nadine', '나딘']],
  [7, ['Zahir', '자히르']],
  [8, ['Hart', '하트']],
  [9, ['Isol', '아이솔']],
  [10, ['Li Dailin', '리 다이린', '리다이린']],
  [11, ['Yuki', '유키']],
  [12, ['Hyejin', '혜진']],
  [13, ['Xiukai', '쇼우']],
  [14, ['Sissela', '시셀라']],
  [15, ['Chiara', '키아라']],
  [16, ['Adriana', '아드리아나']],
  [17, ['Shoichi', '쇼이치']],
  [18, ['Silvia', '실비아']],
  [19, ['Emma', '엠마']],
  [20, ['Lenox', '레녹스']],
  [21, ['Rozzi', '로지']],
  [22, ['Luke', '루크']],
  [23, ['Cathy', '캐시']],
  [24, ['Adela', '아델라']],
  [25, ['Bernice', 'bERnice', '버니스']],
  [26, ['Barbara', '바바라']],
  [27, ['Alex', '알렉스']],
  [28, ['Sua', '수아']],
  [29, ['Leon', '레온']],
  [30, ['Eleven', '일레븐']],
  [31, ['Rio', '리오']],
  [32, ['William', '윌리엄']],
  [33, ['Nicky', '니키']],
  [34, ['Nathapon', '나타폰']],
  [35, ['Jan', '얀']],
  [36, ['Eva', '에바']],
  [37, ['Daniel', '다니엘']],
  [38, ['Jenny', '제니']],
  [39, ['Camilo', '카밀로']],
  [40, ['Chloe', '클로에']],
  [41, ['Johann', '요한']],
  [42, ['Bianca', '비앙카']],
  [43, ['Celine', '셀린']],
  [44, ['Echion', '에키온']],
  [45, ['Mai', '마이']],
  [46, ['Aiden', '에이든']],
  [47, ['Laura', '라우라']],
  [48, ['Tia', '띠아', '티아']],
  [49, ['Felix', '펠릭스']],
  [50, ['Elena', '엘레나']],
  [51, ['Priya', '프리야']],
  [52, ['Adina', '아디나']],
  [53, ['Markus', '마커스']],
  [54, ['Karla', '칼라']],
  [55, ['Estelle', '에스텔']],
  [56, ['Piolo', '피올로']],
  [57, ['Martina', '마르티나']],
  [58, ['Haze', '헤이즈']],
  [59, ['Isaac', '아이작']],
  [60, ['Tazia', '타지아']],
  [61, ['Irem', '이렘']],
  [62, ['Theodore', '테오도르']],
  [63, ['Ly Anh', 'Ly anh', '이안']],
  [64, ['Vanya', '바냐']],
  [65, ['Debi & Marlene', 'Debi and Marlene', '데비&마를렌', '데비와 마를렌']],
  [66, ['Arda', '아르다']],
  [67, ['Abigail', '아비게일']],
  [68, ['Alonso', '알론소']],
  [69, ['Leni', '레니']],
  [70, ['Tsubame', '츠바메']],
  [71, ['Kenneth', '케네스']],
  [72, ['Katja', '카티야']],
  [73, ['Charlotte', '샬럿']],
  [74, ['Darko', '다르코']],
  [75, ['Lenore', '르노어']],
  [76, ['Garnet', '가넷']],
  [77, ['Yumin', '유민']],
  [78, ['Hisui', '히스이']],
  [79, ['Justyna', '유스티나']],
  [80, ['István', 'István', 'Istvan', '이슈트반']],
  [81, ['NiaH', 'Nia', '니아']],
  [82, ['Xuelin', '슈에린']],
  [83, ['Henry', '헨리']],
  [84, ['Blair', '블레어']],
  [85, ['Mirka', '미르카']],
  [86, ['Fenrir', '펜리르']],
  [87, ['Coraline', '코랄라인']],
  [88, ['Bihyung', '비형']],
  [89, ['Craver', 'CravER', '크레이버']],
] as const

export const fanKitCharacterCodeByName = Object.fromEntries(
  fanKitCharacterCodeEntries.flatMap(([code, names]) =>
    names.map((name) => [normalizeCharacterName(name), code]),
  ),
) as Record<string, number>

export function getFanKitCharacterCode(characterName?: string) {
  return fanKitCharacterCodeByName[normalizeCharacterName(characterName)]
}

function normalizeCharacterName(value?: string) {
  return value?.toLowerCase().replace(/[\s._'’`´-]/g, '') ?? ''
}
